### ISSUE TITLE
The "Live Output" should position fixed when scrolling down to see code

### ISSUE THREAD

**Issue by netsi1964** [GoogleChrome/samples#251]
Hi,
Love your site, however the output (Live Output) area of the example code (for instance here [Rest parameters es6](https://googlechrome.github.io/samples/rest-parameters-es6/index.html) ) scrolls out of view as you scroll down to see the actual code which is generating the output.

It would be better if the "Live Output" area change to fixed as the user scrolls it up, that would prevent the "Live Output" area to vanish out of the top of the page.

**Comment by jeffposnick** [comment]
I understand the feedback for that particular sample. It might be more appropriate in that case to provide the Live Output area at the bottom of the page, after the code sample, so that it doesn't push things down.

I don't believe that we'll change the overall template layout, though, as forcing developers to always see the live output area via `position: fixed` or the like would eat up a significant chunk of screen real estate.
