### ISSUE TITLE
SW Sample: Service Worker URL Parameters

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/samples#35]
It should demonstrating registration in which data from the client page is encoded as a URL parameter appended to the SW script URL. The SW then deserializes that URL parameter data and makes use of it.

An example would be a client page that passes in a list of URLs that should be prefetched, as an alternative to a hardcoded a list of prefetch URLs within the SW's `oninstall` handler.

**Comment by jeffposnick** [comment]
@gauntface pointed out that this might be difficult to implement as intended, due to the install only being executed for updated service workers. I guess I assumed that changing the URL parameters appended to the SW script URL in the `register()` would trigger an update, but maybe that's not the case? I'll have to experiment and see.

@gauntface, am I correctly characterizing your concern?

**Comment by gauntface** [comment]
This is a stream of consciousness 

Basically my understanding has been that a service worker is updated when the browser detects a file change. What this approach does is flip that around.

Say we register(sw.js?foo=bar), when the user revisits this page, they'll presumably get the cached page (which still registers sw.js?foo=bar) and in the background the browser will attempt to get sw.js?foo=bar and check for an update.

Let's say for arguments sake we don't cache the page or try the network first before the cache. The page loads, we then register('sw.js?bar=foo'), at this point the browser _might/hopefully_ register this as a new service worker, but in the mean time I presume the browser in the background would still try to update sw.js?foo=bar.

The two issues from above:
- Cached pages want get the updated SW since the update is now in the page in the params
- The browser might waste a request to check on a service worker file before the page is loaded.

**Comment by frequent** [comment]
@jeffposnick - came here looking for ways to pass parameters into an SW via Url. From what I see, the scriptURL is only available after the SW has been activated, no? I was only able to access scriptURL on `self.registration.active.scriptURL` inside my worker. During `install`, I did not find a way to access the url. Is this even possible?

**Comment by jeffposnick** [comment]
You can access the script's full URL, including URL parameters, at any point in the service worker lifecycle via `location`.

There's a small example of using that to deserialize URL parameters at https://github.com/PolymerElements/platinum-sw/blob/master/service-worker.js#L27

**Comment by frequent** [comment]
@jeffposnick Super. Thank you very much for helping out and the example.. I also did not now `importScripts` was supported. Nice, too.

**Comment by markafoltz** [comment]
Closing out this old issue, it looks like it was answered by @jeffposnick at https://github.com/GoogleChrome/samples/issues/35#issuecomment-277726699
